esphome:
  name: aircon
  friendly_name: Aircon

esp32:
  board: esp32dev


# Enable logging
logger:

# Enable Home Assistant API - generate a new key here: https://esphome.io/components/api.html
api:
  encryption:
    key: "QpZTJbJ0Uuv2HDJOQKb9QYDFZyQR9JV7JQmmgVGxx8U="


substitutions:
  device_name: tclac
  humanly_name: TCL Air Conditioner
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  recovery_pass: mKSzmBdt7DAj
  ota_pass: 90cf525a594c8bb2cbf917bc2c2fa058
  uart_rx: GPIO4 #Change to your prefered GPIO
  uart_tx: GPIO3 #Change to your prefered GPIO
  #receive_led: GPIO2
  #transmit_led: GPIO2

packages:
  remote_package:
    url: https://github.com/thedesp/tclac.git     
    ref: master
    files:
      - packages/core.yaml
    refresh: 30s
    
