substitutions:
  # Unique name for this configuration - use only Latin letters and numbers,
  # no spaces or special characters, e.g., "tclac".
  # If you have multiple climate modules, device_name must be changed accordingly,
  # e.g., by appending numbers: tclac1, tclac2, tclac3...
  device_name: tclac

  # Human-readable name for the climate device, displayed in the user interface:
  humanly_name: TCL Air Conditioner

  # Wi-Fi credentials - can alternatively be stored in the "secret" file in ESPHome, otherwise edit here:
  # Name of the Wi-Fi network:
  wifi_ssid: !secret wifi_ssid

  # Wi-Fi password:
  wifi_password: !secret wifi_password

  # Password for recovery mode - the hotspot will then be named: "{device_name} Fallback Hotspot"
  recovery_pass: mKSzmBdt7DAj

  # Password for OTA updates - generated once and used permanently:
  ota_pass: 90cf525a594c8bb2cbf917bc2c2fa058

  # API key for connecting to Home Assistant - generate a new key here: https://esphome.io/components/api.html
  api_key: QpZTJbJ0Uuv2HDJOQKb9QYDFZyQR9JV7JQmmgVGxx8U=

  # GPIO pins of the module to which UART is connected:
  uart_rx: GPIO4 #Change to your prefered GPIO
  uart_tx: GPIO3 #Change to your prefered GPIO

  # GPIO pins for status LEDs (receive/transmit). Only work if "leds" is enabled in "packages".
  # If you don't want to use LEDs, you can enter any values here.
  receive_led: GPIO6
  transmit_led: GPIO4

# Included files - are automatically downloaded and updated from the internet.
# Uncomment the desired options.
# Description of the options:
# - packages/leds.yaml - LEDs to indicate sending/receiving; define pins via receive_led / transmit_led
#
# All entered lines must be exactly at this indentation level - otherwise errors will occur!
packages:
  remote_package:
    url: https://github.com/thedesp/tclac.git
    ref: master
    files:
      # v - Lines must be aligned exactly here, otherwise there will be problems!
      - packages/core.yaml # The core of the whole thing
      # - packages/leds.yaml
    refresh: 30s

# Selected module that will be flashed with this firmware.
# Prepared configurations can be used by removing the comment:

# ESP-01S
esp8266:
  board: esp01_1m

# Hommyn HDN/WFN-02-01 (from the first article)
#esp32:
#  board: esp32-c3-devkitm-1
#  framework:
#    type: arduino

# Status LED - optionally enable if free pins are available
#status_led:
#  pin:
#    number: GPIO5
#    inverted: false